export const STATIC_RESOURCES = [
    { title: 'The Reason I Jump by Naoki Higashida', content: 'Written by a 13-year-old autistic boy, this book provides unique insights into the autistic mind.', link: 'https://en.wikipedia.org/wiki/The_Reason_I_Jump', category: 'EDUCATION' },
    { title: 'NeuroTribes by Steve Silberman', content: 'Award-winning book exploring the history of autism and the neurodiversity movement.', link: 'https://stevesilberman.com/book/neurotribes/', category: 'EDUCATION' },
    { title: 'Uniquely Human by Barry M. Prizant', content: 'A compassionate approach to understanding autistic behaviors as coping mechanisms.', link: 'https://barryprizant.com/books/uniquely-human/', category: 'BEHAVIOR' },
    { title: 'The Whole-Brain Child by Daniel J. Siegel', content: 'Brain-based strategies for nurturing your child\'s developing mind.', link: 'https://drdansiegel.com/book/the-whole-brain-child/', category: 'EDUCATION' },
    { title: 'Look Me in the Eye: My Life with Asperger\'s', content: 'New York Times Bestseller. A touching and hilarious memoir.', link: 'https://en.wikipedia.org/wiki/Look_Me_in_the_Eye', category: 'COMMUNITY' },
    { title: 'Thinking in Pictures by Temple Grandin', content: 'Temple Grandin shares her personal experience with autism and her unique visual thinking style.', link: 'https://www.templegrandin.com/', category: 'EDUCATION' },
    { title: 'Autistic Self Advocacy Network (ASAN)', content: 'Leading organization run by and for autistic people, promoting neurodiversity and self-advocacy.', link: 'https://autisticadvocacy.org', category: 'COMMUNITY' },
    { title: 'Autism Society of America', content: 'Provides advocacy, resources, and support for the autism community.', link: 'https://autismsociety.org/', category: 'COMMUNITY' },
    { title: 'National Autism Association', content: 'Focuses on safety, wandering prevention, and family support services.', link: 'https://nationalautismassociation.org', category: 'COMMUNITY' },
    { title: 'Autism Speaks Resource Guide', content: 'Comprehensive resource database including toolkits.', link: 'https://www.autismspeaks.org/tool-kit', category: 'EDUCATION' },
    { title: 'TACA (The Autism Community in Action)', content: 'Provides education, support, and resources to families.', link: 'https://tacanow.org', category: 'COMMUNITY' },
    { title: 'Autism Research Institute', content: 'Focuses on researching the causes of autism and developing treatments.', link: 'https://www.autism.org/', category: 'EDUCATION' },
    { title: 'Organization for Autism Research (OAR)', content: 'Uses applied science to answer questions that parents, families, and individuals confront daily.', link: 'https://researchautism.org/', category: 'EDUCATION' },
    { title: 'Wrightslaw Special Education Law', content: 'Information about special education law, IEPs, and advocacy.', link: 'https://www.wrightslaw.com', category: 'LEGAL' },
    { title: 'COPAA', content: 'Council of Parent Attorneys and Advocates.', link: 'https://www.copaa.org', category: 'LEGAL' },
    { title: 'Disability Rights Education & Defense Fund', content: 'Leading national civil rights law and policy center.', link: 'https://dredf.org/', category: 'LEGAL' },
    { title: 'Proloquo2Go', content: 'AAC app for communication.', link: 'https://www.assistiveware.com/products/proloquo2go', category: 'THERAPY' },
    { title: 'TouchChat', content: 'Full-featured communication solution.', link: 'https://touchchatapp.com/', category: 'THERAPY' },
    { title: 'Hanen Centre', content: 'Resources for parents to help children communicate.', link: 'http://www.hanen.org/', category: 'THERAPY' },
    { title: 'Floortime (DIR)', content: 'Developmental, Individual-differences, Relationship-based model.', link: 'https://www.icdl.com/dir', category: 'THERAPY' },
    { title: 'Feeding Matters', content: 'Uniting families and healthcare professionals to improve care for children with pediatric feeding disorder.', link: 'https://www.feedingmatters.org/', category: 'NUTRITION' },
    { title: 'Sleep Foundation - Autism', content: 'Guide to autism and sleep.', link: 'https://www.sleepfoundation.org/autism-and-sleep', category: 'SLEEP' },
    { title: 'Autism Services Alabama', content: 'Local support and advocacy for families in Alabama.', link: 'https://www.google.com/search?q=Autism+Society+of+Alabama', category: 'COMMUNITY' },
    { title: 'Autism Services California', content: 'Local support and advocacy for families in California.', link: 'https://www.google.com/search?q=Autism+Society+of+California', category: 'COMMUNITY' },
    { title: 'Autism Services New York', content: 'Local support and advocacy for families in New York.', link: 'https://www.google.com/search?q=Autism+Society+of+New+York', category: 'COMMUNITY' },
    { title: 'Autism Services Texas', content: 'Local support and advocacy for families in Texas.', link: 'https://www.google.com/search?q=Autism+Society+of+Texas', category: 'COMMUNITY' },
    { title: 'IEP Tip: Advocacy Strategy #1', content: 'Essential strategy for navigating the Individualized Education Program process.', link: 'https://www.google.com/search?q=IEP+advocacy+tip+1+autism', category: 'LEGAL' },
    { title: 'Autism Grant Opportunity 2025', content: 'Search for financial assistance programs for therapy and equipment.', link: 'https://www.google.com/search?q=autism+family+grants+2025', category: 'FINANCIAL' },
    { title: 'Behavioral Support: Technique #1', content: 'Evidence-based strategy for positive behavior support at home.', link: 'https://www.google.com/search?q=autism+positive+behavior+support+strategy', category: 'BEHAVIOR' },
    { title: 'Social Skills Groups Autism', content: 'Find local social skills groups and interactive sessions.', link: 'https://www.google.com/search?q=social+skills+groups+autism', category: 'SOCIAL_SKILLS' }
];
