"use client";

import { AlertTriangle, Shield, FileText, Heart } from "lucide-react";
import Link from "next/link";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[var(--background)] pt-16">
      <div className="max-w-3xl mx-auto px-4 py-12">
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-amber-500/10 text-amber-600 dark:text-amber-400 text-sm font-semibold mb-4">
            <AlertTriangle className="w-4 h-4" />
            Important Notice
          </div>
          <h1 className="text-3xl font-bold text-[var(--text)] mb-4">Medical Disclaimer</h1>
          <p className="text-[var(--muted)]">Please read this important information carefully</p>
        </div>

        <div className="bg-[var(--surface)] rounded-2xl border border-[var(--border)] p-6 sm:p-8 shadow-premium space-y-8">
          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-4 flex items-center gap-2">
              <Shield className="w-5 h-5 text-[var(--primary)]" />
              General Disclaimer
            </h2>
            <div className="space-y-4 text-[var(--muted)]">
              <p>
                The information provided on NeuroKid is for <strong className="text-[var(--text)]">general informational and educational purposes only</strong>. 
                It is not intended to be a substitute for professional medical advice, diagnosis, or treatment.
              </p>
              <p>
                Always seek the advice of your physician, therapist, or other qualified health provider with any questions 
                you may have regarding a medical condition or your child's development.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-4 flex items-center gap-2">
              <FileText className="w-5 h-5 text-[var(--primary)]" />
              AI Companion Disclaimer
            </h2>
            <div className="space-y-4 text-[var(--muted)]">
              <p>
                Our AI Companion feature provides <strong className="text-[var(--text)]">general guidance and emotional support</strong>. 
                It is powered by artificial intelligence and should not be considered medical advice.
              </p>
              <ul className="list-disc pl-5 space-y-2">
                <li>The AI does not diagnose conditions or prescribe treatments</li>
                <li>Responses are generated by AI and may not always be accurate</li>
                <li>The AI cannot replace consultation with healthcare professionals</li>
                <li>In emergencies, always call 911 or your local emergency services</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-4 flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-amber-500" />
              Screening Tool Disclaimer
            </h2>
            <div className="space-y-4 text-[var(--muted)]">
              <p>
                The M-CHAT-R/F™ screening tool available on this platform is a <strong className="text-[var(--text)]">preliminary screening instrument</strong>, 
                not a diagnostic tool. A positive screening result does not mean your child has autism.
              </p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Results should be discussed with a qualified healthcare provider</li>
                <li>Only licensed professionals can provide an official autism diagnosis</li>
                <li>Early intervention is beneficial regardless of final diagnosis</li>
                <li>Many children who screen positive do not receive an autism diagnosis</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-4 flex items-center gap-2">
              <Heart className="w-5 h-5 text-red-500" />
              Crisis & Emergency Situations
            </h2>
            <div className="space-y-4 text-[var(--muted)]">
              <p>
                If you or someone you know is in <strong className="text-[var(--text)]">immediate danger or experiencing a mental health emergency</strong>, 
                please take action immediately:
              </p>
              <div className="bg-red-50 dark:bg-red-900/10 rounded-xl border border-red-200 dark:border-red-900/20 p-4">
                <ul className="space-y-2">
                  <li><strong>Emergency Services:</strong> Call 911</li>
                  <li><strong>Suicide & Crisis Lifeline:</strong> Call or text 988</li>
                  <li><strong>Crisis Text Line:</strong> Text HOME to 741741</li>
                </ul>
              </div>
              <p>
                NeuroKid is not equipped to handle emergencies. Our platform and AI features are not monitored in real-time 
                and should never be used as a substitute for emergency services.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--text)] mb-4">Provider Directory Disclaimer</h2>
            <div className="space-y-4 text-[var(--muted)]">
              <p>
                Provider listings in our directory are provided for informational purposes. NeuroKid does not:
              </p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Guarantee the accuracy of provider information</li>
                <li>Endorse or recommend specific providers</li>
                <li>Verify the credentials of all listed providers</li>
                <li>Accept responsibility for outcomes of services provided</li>
              </ul>
              <p>
                Always verify provider credentials and conduct your own research before engaging any healthcare professional.
              </p>
            </div>
          </section>

          <div className="border-t border-[var(--border)] pt-6">
            <p className="text-sm text-[var(--muted)] text-center">
              By using NeuroKid, you acknowledge that you have read and understood this disclaimer. 
              If you have any questions, please contact us.
            </p>
            <p className="text-xs text-[var(--muted)] text-center mt-4">
              Last updated: January 2026
            </p>
          </div>
        </div>

        <div className="mt-8 flex justify-center gap-4">
          <Link
            href="/privacy"
            className="text-sm text-[var(--primary)] hover:underline"
          >
            Privacy Policy
          </Link>
          <span className="text-[var(--muted)]">•</span>
          <Link
            href="/terms"
            className="text-sm text-[var(--primary)] hover:underline"
          >
            Terms of Service
          </Link>
        </div>
      </div>
    </div>
  );
}
